### ISSUE TITLE
Function has keyword-only parameters or annotations

### ISSUE THREAD

**Issue by eafpres** [cleanlab/cleanlab#100]
I'm using the library in Python 3.8 running in Linux under Ubuntu 20.04.
Previously it was working, but now I'm getting the noted error.  Here is the full message:
```
Traceback (most recent call last):

  File "/mnt/c/eaf llc/aa-Analytics and BI/Autonet (Torsten Ostervall)/data_pipeline/production_model.py", line 1456, in <module>
    lnl.fit(X = np.array(train_dict['train_X']),

  File "/home/eafpres/.local/lib/python3.8/site-packages/cleanlab/classification.py", line 384, in fit
    'sample_weight' in inspect.getargspec(self.clf.fit).args:

  File "/usr/lib/python3.8/inspect.py", line 1095, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"

ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
```

The calling code is:
```
lnl = LearningWithNoisyLabels(clf = model, n_jobs = 1)
lnl.fit(X = np.array(train_dict['train_X']),
        s = np.array(train_dict['train_Y']))
```

The model is an xgboost model:

```
  model = xgb.XGBClassifier(colsample_bytree = colsample_bytree,
                            gamma = gamma,
                            learning_rate = learning_rate,
                            max_depth = max_depth,
                            min_child_weight = min_child_weight,
                            n_estimators = n_iters,
                            reg_alpha = reg_alpha,
                            reg_lambda = reg_lambda,
                            subsample = subsample,
                            tree_method = 'exact',
                            objective = objective,
                            booster = 'gbtree',
                            eval_metric = eval_metric,
                            random_state = random_state,
                            num_class = num_class,
                            use_label_encoder = False)
```

There are 3 classes.

I can't find much on this error, any direction would  be welcome.

**Comment by anishathalye** [comment]
Thank you for reporting this. Fixed in 8f9f3f53801c1100a25b458255e134877844e9d0 by switching from [`inspect.getargspec`](https://docs.python.org/3.6/library/inspect.html#inspect.getargspec) to [`inspect.getfullargspec`](https://docs.python.org/3.6/library/inspect.html#inspect.getfullargspec).
