### ISSUE TITLE
Give better error messages when a class has no examples in `find_label_issues`

### ISSUE THREAD

**Issue by anishathalye** [cleanlab/cleanlab#288]
Currently, we produce various internal errors when a class is not represented. We should either support missing classes, or we should produce something like a `ValueError("find_label_issues requires that each class has at least one example")`.

Right now, we produce a variety of internal errors (data-dependent).

# Steps to reproduce

## Example 1

```python
import cleanlab
import numpy as np

labels = np.array([0, 0, 1, 1])
pred_probs = np.array([[0.1, 0.7, 0.2], [0.1, 0.8, 0.1], [0.7, 0.2, 0.1], [0.8, 0.1, 0.1]])
issues = cleanlab.filter.find_label_issues(labels, pred_probs, n_jobs=1)
```

Produces the result:

```
Traceback (most recent call last):
  File ".../error.py", line 6, in <module>
    issues = cleanlab.filter.find_label_issues(labels, pred_probs)
  File ".../src/cleanlab/env/lib/python3.9/site-packages/cleanlab/filter.py", line 457, in find_label_issues
    confident_joint, cl_error_indices = compute_confident_joint(
  File ".../src/cleanlab/env/lib/python3.9/site-packages/cleanlab/count.py", line 435, in compute_confident_joint
    pred_probs_bool = pred_probs >= thresholds - 1e-6
ValueError: operands could not be broadcast together with shapes (4,3) (2,)
```

## Example 2

```python
import cleanlab
import numpy as np

labels = np.array([0, 0])
pred_probs = np.array([[0.3, 0.7], [0.2, 0.8]])
issues = cleanlab.filter.find_label_issues(labels, pred_probs, n_jobs=1)
```

Produces the result:

```
Traceback (most recent call last):
  File ".../error.py", line 6, in <module>
    issues = cleanlab.filter.find_label_issues(labels, pred_probs, n_jobs=1)
  File ".../src/cleanlab/env/lib/python3.9/site-packages/cleanlab/filter.py", line 561, in find_label_issues
    label_issues_masks_per_class = [_prune_by_count(k, args) for k in range(K)]
  File ".../src/cleanlab/env/lib/python3.9/site-packages/cleanlab/filter.py", line 561, in <listcomp>
    label_issues_masks_per_class = [_prune_by_count(k, args) for k in range(K)]
  File ".../src/cleanlab/env/lib/python3.9/site-packages/cleanlab/filter.py", line 204, in _prune_by_count
    if label_counts[k] <= min_examples_per_class:  # No prune if not at least min_examples_per_class
IndexError: index 1 is out of bounds for axis 0 with size 1
```

# Additional information

- **Cleanlab version**: 2.0.0 (and also reproduced on master = 5e0b62d79790028c6c69a76c6af28c813a27ace5, though the stack traces and exceptions are slightly different there)
- **Operating system**: macOS 12.1, shouldn't be relevant here
- **Python version**: Python 3.9.12

**Comment by sidshrivastav** [comment]
@anishathalye do we just need to raise error `ValueError("find_label_issues requires that each class has at least one example")` for these two cases?

**Comment by anishathalye** [comment]
I am not sure what you mean by "these two cases."

We already raise warnings in two places [[1](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/filter.py#L165), [2](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/filter.py#L206)] when a class has too few examples (under min examples per class). We could raise an exception there if a class has zero examples. Or maybe it's cleaner to do it in another spot; that needs to be investigated. Also need to make sure that the exception propagates properly under both `n_jobs=1` (no multiprocessing) and `n_jobs>1` (multiprocessing).

**Comment by sidshrivastav** [comment]
Hey, thanks for explaining the requirement, I have tried to debug the code, as I can see we use [label_counts](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/filter.py#L451), which is Number of examples in each class of labels, [K](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/filter.py#L453) which is Number of classes labels and `min_examples_per_class` which is by default 1.

`label_counts` is value_count which for first example is [2, 2], now on [line](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/filter.py#L565) we pass `k` where it is `range(K)` means [0,1,2,3], we don't have element on index 2 and 3 for `label_count`. so when we do this [label_counts[k]](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/filter.py#L204), it will throw exception.

Now we can add this condition, where `if len(label_counts) < k: raise excpetion` in `find_label_issues`. 

I am not sure that it is correct but that will throw warning for given example.

**Comment by jwmueller** [comment]
Thanks for volunteering to contribute @sidshrivastav 
we could definitely use your help improving this library!!

For this specific issue though, I'm already handling it as part of another PR as it is very simple.

**Comment by sidshrivastav** [comment]
@jwmueller thanks for updating
